import React,{useEffect,useRef,useState}from"react";import html2canvas from"html2canvas";
const S=.5,P={A0:[84.1,118.9],A1:[59.4,84.1],A2:[42,59.4]},W={w1a:["Wall 1 — 22 m",2200,240],w1b:["Wall 1 — 15.7 m",1570,240],w2a:["Wall 2 — 15.7 m",1570,240],w2b:["Wall 2 — 9.4 m",940,240],w3:["Wall 3 — 9.4 m",940,240]};
const id=()=>crypto.randomUUID?.()||Math.random().toString(36).slice(2);
function db(){return new Promise((ok,no)=>{let r=indexedDB.open("wall-planner",1);r.onupgradeneeded=()=>r.result.createObjectStore("walls");r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
async function get(k){let d=await db();return new Promise((ok,no)=>{let r=d.transaction("walls").objectStore("walls").get(k);r.onsuccess=()=>ok(r.result||[]);r.onerror=()=>no(r.error)})}
async function put(k,v){let d=await db();return new Promise((ok,no)=>{let t=d.transaction("walls","readwrite");t.objectStore("walls").put(v,k);t.oncomplete=ok;t.onerror=()=>no(t.error)})}
export default function App(){const[k,setK]=useState("w1a"),[tiles,setTiles]=useState([]),[ready,setReady]=useState(false),[sel,setSel]=useState(null),[clean,setClean]=useState(false);const ref=useRef(),drag=useRef(),timer=useRef();const wall=W[k];
useEffect(()=>{setReady(false);get(k).then(x=>{setTiles(x);setReady(true)})},[k]);useEffect(()=>{if(ready)put(k,tiles)},[tiles,k,ready]);
const size=t=>{let[a,b]=P[t.s];return t.o==="P"?[a,b]:[b,a]};const controls=x=>{setSel(x);clearTimeout(timer.current);timer.current=setTimeout(()=>setSel(null),3500)};
function add(s){let[a,b]=P[s],o=Math.random()>.45?"P":"L",[ww,hh]=o==="P"?[a,b]:[b,a];setTiles(x=>[...x,{id:id(),s,o,x:Math.random()*(wall[1]-ww),y:Math.random()*(wall[2]-hh)}])}
function rotate(i){setTiles(x=>x.map(t=>t.id===i?{...t,o:t.o==="P"?"L":"P"}:t));controls(i)}function del(i){setTiles(x=>x.filter(t=>t.id!==i));setSel(null)}
function photo(i){let n=document.createElement("input");n.type="file";n.accept="image/*";n.onchange=()=>{let f=n.files?.[0];if(!f)return;let r=new FileReader;r.onload=()=>setTiles(x=>x.map(t=>t.id===i?{...t,img:r.result}:t));r.readAsDataURL(f)};n.click()}
function down(e,t){if(clean)return;e.preventDefault();controls(t.id);let r=ref.current.getBoundingClientRect();drag.current={id:t.id,dx:(e.clientX-r.left)/S-t.x,dy:(e.clientY-r.top)/S-t.y}}
function move(e){if(!drag.current)return;let r=ref.current.getBoundingClientRect(),d=drag.current;setTiles(x=>x.map(t=>{if(t.id!==d.id)return t;let[w,h]=size(t),nx=(e.clientX-r.left)/S-d.dx,ny=(e.clientY-r.top)/S-d.dy;return{...t,x:Math.max(0,Math.min(wall[1]-w,Math.round(nx))),y:Math.max(0,Math.min(wall[2]-h,Math.round(ny)))}}))}
async function png(){setClean(true);setSel(null);await new Promise(r=>setTimeout(r,80));let c=await html2canvas(ref.current,{backgroundColor:"#fff",scale:2}),a=document.createElement("a");a.download=wall[0].replaceAll(" ","_")+".png";a.href=c.toDataURL("image/png");a.click();setClean(false)}
function backup(){let b=new Blob([JSON.stringify({version:1,wall:k,tiles},null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(b);a.download=k+"-backup.json";a.click();URL.revokeObjectURL(a.href)}
function restore(){let n=document.createElement("input");n.type="file";n.accept=".json";n.onchange=async()=>{try{let j=JSON.parse(await n.files[0].text()),x=Array.isArray(j)?j:j.tiles;if(!Array.isArray(x))throw 0;setTiles(x)}catch{alert("Invalid wall backup")}};n.click()}
return <main><header><div><h1>Exhibition Wall Planner</h1><p>A0 / A1 / A2 · portrait + landscape · autosaved in this browser</p></div><select value={k} onChange={e=>setK(e.target.value)}>{Object.entries(W).map(([x,w])=><option value={x} key={x}>{w[0]} × 2.40 m</option>)}</select></header>
<section className="bar"><div>{Object.keys(P).map(s=><button key={s} onClick={()=>add(s)}>Add {s}</button>)}</div><div><button onClick={()=>setClean(!clean)}>{clean?"Edit":"Clean preview"}</button><button onClick={png}>Export PNG</button><button onClick={backup}>Backup JSON</button><button onClick={restore}>Restore JSON</button></div></section>
<div className="meta"><b>{wall[0]}</b> · {(wall[1]/100).toFixed(1)} × 2.40 m <span>{tiles.length} photographs</span></div><div className="scroll"><div ref={ref} className="wall" style={{width:wall[1]*S,height:wall[2]*S}} onMouseMove={move} onMouseUp={()=>drag.current=null} onMouseLeave={()=>drag.current=null}><div className="eye"/>{tiles.map(t=>{let[w,h]=size(t);return <div key={t.id} className={"tile "+(sel===t.id?"selected":"")} style={{left:t.x*S,top:t.y*S,width:w*S,height:h*S,backgroundImage:t.img?`url("${t.img}")`:"none"}} onMouseDown={e=>down(e,t)} onClick={()=>controls(t.id)} onDoubleClick={()=>photo(t.id)}>{!t.img&&<span>{t.s}<small>{t.o==="P"?"portrait":"landscape"}</small></span>}{!clean&&sel===t.id&&<div className="actions" onMouseDown={e=>e.stopPropagation()}><button onClick={()=>photo(t.id)}>{t.img?"Replace":"Photo"}</button><button onClick={()=>rotate(t.id)}>Rotate</button><button className="danger" onClick={()=>del(t.id)}>Delete</button></div>}</div>})}</div></div><footer>Double-click a frame to add/replace a photograph · click for controls · drag to position</footer></main>}